services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dokploy-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/supabase-projects:/app/supabase-projects
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
